### ISSUE TITLE
Maximum sequence numbers for AES-CCM

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/OSCOAP#33]
TLS 1.3 has significantly tighter limits for the number of messages that can be sent.

"For AES-GCM, up to 2^24.5 full-size records (about 24 million) may be encrypted on a given connection while keeping a safety margin of approximately 2^-57 for Authenticated Encryption (AE) security."

But this is more a COSE question than OSCOAP.

**Comment by jimsch** [comment]
Looking for some numbers to quantify this, I have found the following so far.  I intend to keep looking.

** Authentication is lost after 2^64 blocks
** Tags are going to be birthday attacked at 2^n/2 where n is the length of the tag being used
** Total invocations is 2^61 of the block cipher - Per NIST document.  Invocations are going to be 2 per message/block size + small constant for each message.
