### ISSUE TITLE
Deduplicate context details

### ISSUE THREAD

**Issue by chrysn** [EricssonResearch/OSCOAP#35]
The repetitive context information requires implementors to check whether the lines that are similar on the first glance are actually the same, and IMO make the document hard to read.

Would you consider defining "the" server security context and "the" client security context initially, and then only stating deviating cases (eg. in 4.1.2: "server security context: *the* server security context, but with those modifications: / - Recipient key: F8 ...")? I think it would improve usability.

**Comment by fpalombini** [comment]
Thanks for the feedback :)
